# Generated by Django 3.1.2 on 2020-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cell_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
